In [6]:
import numpy as np

In [7]:
##create array von einer Liste onedimensional


In [8]:
x = np.array([5, 4, -7, 11])
print(x)


[ 5  4 -7 11]


In [9]:
x = np.array([6,7,9,-3])
print(x)

[ 6  7  9 -3]


In [10]:
##zweidimensionaler area von liste (zweidimensional wegen der zwei eckigen Klammern, bei drei [[[ haben wir einen dreidimensionalen Array


In [11]:
y = np.array([[4, 5, 0], [3, 7, 9], [2, 1, 2]])
print(y)

[[4 5 0]
 [3 7 9]
 [2 1 2]]


In [12]:
a = np.array([[3, 6, 6], [5, 7, 9], [8, 1, 2], [3, 4, 4]])
print(a)

[[3 6 6]
 [5 7 9]
 [8 1 2]
 [3 4 4]]


In [13]:
##dreidimensionaler array

In [14]:
z = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]])
print(z)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [15]:
z = np.array([[[1,2,3,4], [4,5,6,7], [7,8,9,10]], [[10,11,12,13], [13,14,15,16], [16,17,18,19]]])
print(z)

[[[ 1  2  3  4]
  [ 4  5  6  7]
  [ 7  8  9 10]]

 [[10 11 12 13]
  [13 14 15 16]
  [16 17 18 19]]]


In [16]:
###array erstellen mit np.arange (zehn zahlen, geht immer bei 0 los also 0 bis 9).reshape 2 rows, 5 coloms

##treedimensional array
##layer, rows, coloms

In [17]:
b = np.arange(10).reshape(2, 5) 
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [18]:
b = np.arange(10).reshape(5, 2) 
print(b)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [19]:
type(b)

numpy.ndarray

In [20]:
##array ist von numpy

In [21]:
##shape checken --> rows and coloms bekommt man Angaben dazu
#b.shape

In [22]:
b.shape

(5, 2)

In [23]:
b.size

10

In [24]:
b.ndim

2

Exercise1:Create a 3-dimensional array using np.arange() and reshape and check for shape, size, dimension

In [25]:
a = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]])
print(z)

[[[ 1  2  3  4]
  [ 4  5  6  7]
  [ 7  8  9 10]]

 [[10 11 12 13]
  [13 14 15 16]
  [16 17 18 19]]]


In [26]:
z = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]])
print(z)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [27]:
##dreidimensionaler array (layer, row, coloms) muss in der range der Zahlen sein hier 3*3*2 passt in 1-19 = 18

In [28]:
b = np.arange(1, 19).reshape(3, 3, 2) 
print(b)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]


In [29]:
b.shape

(3, 3, 2)

In [30]:
b.size

18

Exercise2:Extract the value 15 from the z array above by indexing

In [31]:
 z = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]])
print(z)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [32]:
##array slice  index 

In [33]:
z[1, 1, 2]

15

In [34]:
##second layer, thrid row, all coloms bedeutet :

In [35]:
z[1, 2, :]

array([16, 17, 18])

In [36]:
##first and second raw (n+1) and all coloms, : bis zu der Zahl, aber die Zahl ist immer nicht mehr dabei

In [37]:
y[:2, :]

array([[4, 5, 0],
       [3, 7, 9]])

In [38]:
##second and third and all coloms

In [39]:
y[1:, :]

array([[3, 7, 9],
       [2, 1, 2]])

Exercise3:Extract the 2nd layer, first and 2nd rows and all columns from the z array above by slice and indexing

In [40]:
z[1, :2, :]

array([[10, 11, 12],
       [13, 14, 15]])

In [41]:
##oder

In [42]:
z[1, 0:2, :]

array([[10, 11, 12],
       [13, 14, 15]])

In [43]:
##vectorizing (x also für jedes element aus array x) and summarizing

In [44]:
x+2

array([ 8,  9, 11, -1])

In [45]:
x-1

array([ 5,  6,  8, -4])

In [46]:
##hoch 2

In [47]:
x**2

array([36, 49, 81,  9])

In [48]:
b-1

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [49]:
##vectorising by functions abs für absolute werte des Arrays

In [50]:
np.abs(x)

array([6, 7, 9, 3])

In [51]:
np.max(x)

9

In [52]:
np.median(x)

6.5

Exercise4: Write a Python program to find the median of a given array of numbers with for and if loop

Exercise5: Write a Python program to find the median of a given array of numbers using vectorizing

In [53]:
##Aufgabe 4 length_x = len(x)

In [54]:
 z = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]])
print(z)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [55]:
lenght_z = len(z)
print(lenght_z)

2


In [56]:
m = [2,3,5,7,8,9,11]

##using for loop

array_len = len(m)
if array_len % 2 == 0:
    median = (m[int(array_len/2)] + m[int(array_len/2 -1 )]/2)
else:
    median = m[int(array_len/2)]
print(median)

7


In [57]:
##aus dem Internet
def median(z):
    sortedz = sorted(z)
    zLen = len(z)
    index = (zLen - 1) // 2
   
    if (lstLen % 2):
        return sortedz[index]
    else:
        return (sortedz[index] + sortedz[index + 1])/2.0

In [58]:
##median einfach gelöst 

In [59]:
np.median(m)

7.0

In [5]:
##Aufgabe 5
##conditional operator --> always false or true

In [60]:
x<5 

array([False, False, False,  True])

In [61]:
x==11

array([False, False, False, False])

In [62]:
~(x > 1)

array([False, False, False,  True])

In [ ]:
##masks for subsetting

In [63]:
x[x < 5]

array([-3])

In [64]:
x[x < 5]=40
x


array([ 6,  7,  9, 40])

Exercise6: Substitute the values from array x which are not greater than 20,or equal to 11 with 30 (use logical operator not and or)

In [68]:
x[~(x>20) | (x==11)]=30
x

array([30, 30, 30, 40])

In [ ]:
np.sum(x)

In [ ]:
np.sum(x<35)

In [ ]:
np.sum(y, axis=0)

In [ ]:
np.sum(y, axis=1)

In [ ]:
##row-column
np.sum(z, axis=0)

In [ ]:
##column-layer
np.sum(z, axis=1)

In [ ]:
##row-layer
np.sum(z, axis=2)

Exercise7: Calculate the mean of all column in each layer from array z.

In [ ]:
## ploting an array

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
h = y.flatten()
h

In [ ]:
plt.hist(h);

In [ ]:
plt.plot(y[1, :]);

In [ ]:
plt.plot(y[:, 1]);

In [ ]:
plt.plot(y);

In [ ]:
plt.imshow(y);

In [ ]:
##practice with plotting on different arrays

In [ ]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

plt.hist(data, bins=[0,2,4,6,8,10])
plt.title('My Histogram')
plt.xlabel('Interval')
plt.ylabel('Frequency')
plt.show()


Exercise8: Given an 2D array of numbers, plot a graph that displays the sum of each element in the column.


Reference: https://docs.python.org
https://geobgu.xyz/py/numpy.html 