In [ ]:
##nicht vergessen import numpy as np

In [2]:
import numpy as np

In [ ]:
##create array von einer Liste onedimensional

In [3]:
x = np.array([5, 4, -7, 11])
print(x)


[ 5  4 -7 11]


In [ ]:
##zweidimensionaler area von liste (zweidimensional wegen der zwei eckigen Klammern, 
#bei drei [[[ haben wir einen dreidimensionalen

In [4]:
y = np.array([[4, 5, 0], [3, 7, 9], [2, 1, 2]])
print(y)

[[4 5 0]
 [3 7 9]
 [2 1 2]]


In [ ]:
##dreidimensionaler array

In [5]:
z = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]])
print(z)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [ ]:
###array erstellen mit np.arange(10).reshape(2, 5)
#np.arange (zehn zahlen, geht immer bei 0 los also 0 bis 9).reshape 
#2 rows/Zeilen, 5 coloms/Spalten

##treedimensional array
##layer, rows, coloms

In [6]:
b = np.arange(10).reshape(2, 5) 
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [7]:
type(b)

numpy.ndarray

In [ ]:
##-->array ist von numpy

In [ ]:
##shape checken --> rows and coloms bekommt man Angaben dazu
#b.shape

In [8]:
b.shape

(2, 5)

In [ ]:
##mit b.size kann die Größe des Arrays ausgegeben werden

In [9]:
b.size

10

In [ ]:
##numpy.ndarray.ndim() function return the number of dimensions of an array.

In [10]:
b.ndim

2

Exercise1:Create a 3-dimensional array using np.arange() and reshape and check for shape, size, dimension

In [4]:
z.ndim

3

In [ ]:
##dreidimensionaler array (layer, row, coloms) 
#muss in der range der Zahlen sein hier 3*3*2 passt in 1-19 = 18

In [5]:
c = np.arange(1, 19).reshape((3, 3, 2))
print(c)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]


In [9]:
c.shape

(3, 3, 2)

In [10]:
c.size

18

In [11]:
c.ndim

3

In [7]:
d = np.arange(1, 49).reshape((3, 4, 4))
print(d)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]

 [[33 34 35 36]
  [37 38 39 40]
  [41 42 43 44]
  [45 46 47 48]]]


Exercise2:Extract the value 15 from the z array above by indexing

In [13]:
z = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]])
print(z)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [ ]:
#layer/row/colom --> z[1,1,2]
##Layer 1 --> also der 2, weil ja bei 0 los gezält wird, 
#row 1 entspricht der 2. und spalte die 2. also hier die 3. weil ja bei 0 los gezählt wird

In [14]:
z[1, 1, 2]


15

In [12]:
##array slice

In [13]:
z[1, 2, :]

array([16, 17, 18])

In [27]:
y = np.array([[4, 5, 0], [3, 7, 9], [2, 1, 2]])
print(y)


[[4 5 0]
 [3 7 9]
 [2 1 2]]


In [ ]:
##zeile und spalte, wobei die letzte also 2. excluded ist :davor bedeutet excluded, 
#:nach der Zahl ist die Zahl drinnen

In [19]:
y[:2, :]

array([[4, 5, 0],
       [3, 7, 9]])

In [ ]:
##zeile und spalte, zeile ab der 1. , also 1. mit included und alle spalten

In [22]:
y[1:, :]

array([[3, 7, 9],
       [2, 1, 2]])

Exercise3:Extract the 2nd layer, first and 2nd rows and all columns from the z array above by slice and indexing

In [23]:
z[1, 0:2, :]

array([[10, 11, 12],
       [13, 14, 15]])

In [16]:
##vectorizing and summarizing

In [29]:
y+2

array([[ 6,  7,  2],
       [ 5,  9, 11],
       [ 4,  3,  4]])

In [30]:
y-1

array([[ 3,  4, -1],
       [ 2,  6,  8],
       [ 1,  0,  1]])

In [31]:
y**2

array([[16, 25,  0],
       [ 9, 49, 81],
       [ 4,  1,  4]])

In [ ]:
##vectorising by functions abs für absolute werte des Arrays

In [32]:
np.abs(y)

array([[4, 5, 0],
       [3, 7, 9],
       [2, 1, 2]])

In [33]:
np.max(y)

9

In [35]:
np.median(y)

3.0

Exercise4: Write a Python program to find the median of a given array of numbers with for and if loop

Exercise5: Write a Python program to find the median of a given array of numbers using vectorizing

In [ ]:
##Aufgabe 4

In [40]:
m=[2,3,5,7,8,9,11]

#using for loop

array_len = len(m)

if array_len % 2 == 0:
    median = (m[int(array_len/2)] + m[int(array_len/2 -1)])/2
else:
    median = m[int(array_len/2)]

print(median)

7


In [ ]:
#Aufgabe 5

In [ ]:
##median einfach gelöst 


In [37]:
np.median(m)

7.0

In [51]:
x<5 

array([False,  True,  True, False])

In [ ]:
##conditional operator --> always false or true

In [52]:
x==11

array([False, False, False,  True])

In [25]:
~(x > 1)

array([False, False,  True, False])

In [26]:
##masks for subsetting

In [27]:
x[x < 5]

array([ 4, -7])

In [28]:
x[x < 5]=40
x


array([ 5, 40, 40, 11])

Exercise6: Substitute the values from array x which are not greater than 20,or equal to 11 with 30 (use logical operator not and or)

In [50]:
x = np.array([5, 4, -7, 11])
print(x)


[ 5  4 -7 11]


In [ ]:
or ist | 

In [45]:
x[~(x > 20)| (x==11)]=30
x

array([30, 30, 30, 30])

In [46]:
np.sum(x)

120

In [47]:
np.sum(x<35)

4

In [ ]:
##row-column

In [48]:
np.sum(y, axis=0)

array([ 9, 13, 11])

In [ ]:
##column-layer

In [49]:
np.sum(y, axis=1)

array([ 9, 19,  5])

In [ ]:
##row-layer

In [53]:
np.sum(z, axis=2)

array([[ 6, 15, 24],
       [33, 42, 51]])

Reference: https://jupyter.org
https://the-turing-way.netlify.app/communication/binder/zero-to-binder.html
https://docs.python.org
https://geobgu.xyz/py/
